baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'TTL256'
theme = 'hugo-book'

[menu]
[[menu.after]]
	name = 'Github'
	url = 'https://github.com/ttl256'
	weight = 10
[[menu.after]]
	name = 'Telegram'
	url = 'https://t.me/ttl256'
	weight = 20

[params]
	BookTheme = 'auto'
	BookToC = true
	BookLogo = '/favicon.png'
	BookMenuBundle = '/menu'
	BookDateFormat = '2006-01-02'
	BookSearch = true
